### ISSUE TITLE
invalid sources

### ISSUE THREAD

**Issue by 0xSolanaceae** [spyboy-productions/Valid8Proxy#3]
your sources are invalid

**Comment by thisisshubhamkumar** [comment]
what do you mean? works for me!!

**Comment by 0xSolanaceae** [comment]
```py
proxy_urls = [
        'https://www.sslproxies.org/',
        'https://www.google-proxy.net/',
        'https://free-proxy-list.net/anonymous-proxy.html',
        'https://free-proxy-list.net/uk-proxy.html',
        'https://www.us-proxy.org/',
        'https://free-proxy-list.net/'
    ]
```

You can no longer scrape from these sources, as they redirect to a main page.

**Comment by thisisshubhamkumar** [comment]
As I mentioned earlier each provided proxy URL works the way it should. Have you been able to run the tool yet? If it's not working, please attach a screenshot of the error.
