### ISSUE TITLE
unable to locate 

### ISSUE THREAD

**Issue by h1br0** [spyboy-productions/Valid8Proxy#6]
![20241030_212749](https://github.com/user-attachments/assets/23e3f995-bd90-4656-a970-2bcbef4abb7e)
or maybe i did something wrong but i tried it on my pc and 2 vm and they couldn't locate and i saw a video on it did it step by step maybe 6 times

**Comment by thisisshubhamkumar** [comment]
you combined sudo apt install git clone https://github.com/..., which led to apt trying to install packages named "git," "clone," and the URL, resulting in the "Unable to locate package" errors.

**Comment by h1br0** [comment]
thanx

**Comment by h1br0** [comment]
also people might have problems i they didn't install git first that's why i tried sudo install on my vm but i remembered i didn't have git or python
